// content/insights.js
// Injects a Gemini-generated "AI Insights" line into the user's private
// profile dashboard. Private surface, unverifiable by any third party — so
// on-concept for Mathify.
(function () {
  if (window.__mathifyInsightsLoaded) return;
  window.__mathifyInsightsLoaded = true;

  const MARK = "data-mathify-injected-insights";
  let injecting = false;

  function shouldRun() {
    // Only inject on the user's own profile page.
    return /^\/in\/[^/]+\/?$/.test(location.pathname);
  }

  function findAnchor() {
    // Walk text nodes looking for a leaf "Your dashboard" label, then return
    // the nearest section/aside ancestor.
    const tw = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, {
      acceptNode: (n) =>
        n.nodeValue && /your dashboard/i.test(n.nodeValue.trim())
          ? NodeFilter.FILTER_ACCEPT
          : NodeFilter.FILTER_REJECT,
    });
    let n;
    while ((n = tw.nextNode())) {
      const t = (n.nodeValue || "").trim().toLowerCase();
      if (t !== "your dashboard") continue;
      let cur = n.parentElement;
      for (let i = 0; i < 8 && cur; i++) {
        if (cur.tagName === "SECTION" || cur.tagName === "ASIDE") return cur;
        cur = cur.parentElement;
      }
      return n.parentElement;
    }
    return null;
  }

  function buildTile(line) {
    const wrap = document.createElement("div");
    wrap.setAttribute(MARK, "1");
    wrap.setAttribute("data-mathify-skip", "1");
    wrap.className = "mathify-insights-tile";

    const head = document.createElement("div");
    head.className = "mathify-insights-head";
    head.setAttribute("data-mathify-skip", "1");
    head.innerHTML =
      '<span class="mathify-insights-spark">✨</span>' +
      '<span class="mathify-insights-label">AI Insights</span>' +
      '<span class="mathify-insights-private">Private to you</span>';

    const body = document.createElement("div");
    body.className = "mathify-insights-body";
    body.setAttribute("data-mathify-skip", "1");
    body.textContent = line;

    const sub = document.createElement("div");
    sub.className = "mathify-insights-sub";
    sub.setAttribute("data-mathify-skip", "1");
    sub.textContent = "Generated by Gemini · refreshes daily";

    wrap.appendChild(head);
    wrap.appendChild(body);
    wrap.appendChild(sub);
    return wrap;
  }

  async function maybeInject() {
    if (!shouldRun()) {
      removeInjected();
      return;
    }
    if (injecting) return;
    if (document.querySelector(`[${MARK}]`)) return;
    if (!window.__mathifyGemini) return;

    const settings = await new Promise((r) =>
      chrome.storage.local.get({ enabled: true, injectInsights: true }, r)
    );
    if (!settings.enabled || !settings.injectInsights) {
      removeInjected();
      return;
    }

    injecting = true;
    try {
      const anchor = findAnchor();
      if (!anchor) return;
      const line = await window.__mathifyGemini.getInsightsLine();
      if (!shouldRun()) return;
      if (document.querySelector(`[${MARK}]`)) return;
      const tile = buildTile(line);
      anchor.parentElement.insertBefore(tile, anchor.nextSibling);
    } catch (e) {
      console.warn("[mathify] insights inject error", e);
    } finally {
      injecting = false;
    }
  }

  function removeInjected() {
    document.querySelectorAll(`[${MARK}]`).forEach((el) => el.remove());
  }

  window.__mathifyInsights = { maybeInject, removeInjected };
  console.log("[mathify] insights.js loaded");
})();
